set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

" ---------------------------------------------------------------------------
" vim-plug (Windows)
"
" Install vim-plug to:
"   %USERPROFILE%\vimfiles\autoload\plug.vim
"
" PowerShell:
"   iwr -useb https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim `
"     -OutFile $env:USERPROFILE\vimfiles\autoload\plug.vim
"
" Then in Vim:
"   :PlugInstall
" ---------------------------------------------------------------------------

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction

call plug#begin('~/vimfiles/plugged')

" Core plugins
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'Lokaltog/powerline-fonts' "requires the powerline fonts to be installed and activated
Plug 'Lokaltog/vim-easymotion'
Plug 'kien/ctrlp.vim'
Plug 'terryma/vim-multiple-cursors'

if has("python")
    "Plug 'severin-lemaignan/vim-minimap'
    "Plug 'Valloric/YouCompleteMe'
    Plug 'Valloric/MatchTagAlways'
endif

call plug#end()
filetype plugin indent on    " required

" Brief help:
" :PlugInstall   - installs plugins
" :PlugUpdate    - updates plugins
" :PlugClean     - removes unused plugins
" :PlugStatus    - checks plugin status

inoremap jk <ESC>
inoremap kj <ESC>

map <F11> <Esc>:call libcallnr("gvimfullscreen.dll", "ToggleFullScreen", 0)<CR>y

set tabstop=4
set noexpandtab
set shiftwidth=4
set autoindent
set softtabstop=4

set background=dark
set number
set t_Co=256
set laststatus=2
set ttimeoutlen=50
set encoding=utf-8

set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar

set background=dark

set directory=.,$TEMP

syntax on
filetype indent plugin on

let g:mta_filetypes = {
    \ 'html' : 1,
    \ 'xhtml' : 1,
    \ 'xml' : 1,
    \ 'jinja' : 1,
    \ 'php' : 1,
    \}

highlight Pmenu ctermfg=blue ctermbg=black

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme = "wombat"

if has('gui_running')
    set guioptions-=T  " no toolbar

    if has('gui_win32')
        set guifont=Inconsolata_for_Powerline:h11:cANSI
    else
        set guifont=Inconsolata\ for\ Powerline\ 11
    endif
endif

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"
